[package]
name = "flif"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "Apache-2.0"

[dependencies]
quick-error = "1.1.0"
podio = "0.1.5"
flate2 = "0.2.14"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"
